apiVersion: v1
kind: Service
metadata:
  name: {{appName}}
  labels:
    name: {{appName}}
    visualize: "true"
spec:
  ports:
    - port: 8081
  selector:
    name: {{appName}}
  type: NodePort
---
###########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /helloWorld/*
        backend:
          serviceName: helloworld
          servicePort: 8081
      - path: /helloWorld/.*
        backend:
          serviceName: helloworld
          servicePort: 8081
      - path: /message1
        backend:
          serviceName: helloworld
          servicePort: 8081
      - path: /claimant
        backend:
          serviceName: claimantservice
          servicePort: 8082
      - path: /message
        backend:
          serviceName: claimantservice
          servicePort: 8082    
---